spring:
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:keycloak-photoz-example
    platform: h2
  h2:
    console:
      enabled: true
  jpa:
    dialect: org.hibernate.dialect.H2Dialect
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

keycloak:
  auth-server-url: https://keycloakpoc-test.jbhunt.com/auth
  realm: photoz
  bearer-only: true
  resource: photoz-restful-api
  credentials:
    secret: secret
  ssl-required: external
  policy-enforcer-config:
    paths:
    - name: Album Resource
      path: /album/{id}
      methods:
      - method: DELETE
        scopes:
        - album:delete
      - method: GET
        scopes:
        - album:view
    - name: Album Resource
      path: /album/shares
      enforcement-mode: DISABLED
    - path: /profile
    - name: Admin Resources
      path: /admin/*
  securityConstraints:
  - authRoles:
    - user
    securityCollections:
    - name: All Resources
      patterns:
      - /*
  - authRoles:
    - admin
    securityCollections:
    - name: All Resources
      patterns:
      - /*

server:
  port: 8081
  servlet:
    context-path: /photoz-restful-api
